# Generated by Django 4.1.9 on 2023-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_No', models.IntegerField(unique=True)),
                ('Div', models.CharField(max_length=50)),
                ('Mentor', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=50)),
                ('Enrollment', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('DM_T1', models.FloatField()),
                ('DM_T2', models.FloatField()),
                ('DM_T3', models.FloatField()),
                ('DM_T4', models.FloatField()),
                ('FSD_2_T1', models.FloatField()),
                ('FSD_2_T2', models.FloatField()),
                ('FSD_2_T3', models.FloatField()),
                ('FSD_2_T4', models.FloatField()),
                ('TOC_T1', models.FloatField()),
                ('TOC_T2', models.FloatField()),
                ('TOC_T3', models.FloatField()),
                ('TOC_T4', models.FloatField()),
                ('FCSP_2_T1', models.FloatField()),
                ('FCSP_2_T2', models.FloatField()),
                ('FCSP_2_T3', models.FloatField()),
                ('FCSP_2_T4', models.FloatField()),
                ('COA_T1', models.FloatField()),
                ('COA_T2', models.FloatField()),
                ('COA_T3', models.FloatField()),
                ('COA_T4', models.FloatField()),
            ],
        ),
    ]
