# Generated by Django 4.1.9 on 2023-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='Enrollment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='Roll_No',
            field=models.IntegerField(),
        ),
    ]
